teams:
-
# The Id of the custom Team
  id: 2
  name: 'GOC'
  min_players: 4
  spawn_chance: 35
  spawn_wave: ChaosInsurgency
  spawn_position:
    x: 63
    y: 992
    z: -50
  cassie_message: ''
  cassie_translation: ''
  import_roles:
  roles:
  -
  # The maximum number of players that can have this role in this wave
    max_players: 2
    spawn_settings: 
    id: 1
    name: ''
    override_role_name: false
    nickname: ''
    custom_info: ''
    badge_name: ''
    badge_color: ''
    role: ChaosRepressor
    team: 
    role_appearance: ChaosRepressor
    is_friend_of: []
    health:
      amount: 125
      maximum: 125
      hume_shield: 0
      hume_shield_regeneration_amount: 0
      hume_shield_regeneration_delay: 0
    ahp:
      amount: 0
      limit: 0
      decay: 0
      efficacy: 0
      sustain: 0
      persistant: false
    effects: []
    stamina:
      regen_multiplier: 1
      usage_multiplier: 1
      infinite: false
    max_scp330_candies: 2
    can_escape: false
    role_after_escape:
    scale:
      x: 1
      y: 1
      z: 1
    spawn_broadcast:
    spawn_broadcast_duration: 15
    spawn_hint: ''
    spawn_hint_duration: 0
    custom_inventory_limits:
      Medical: 2
    inventory:
    custom_items_inventory: []
    ammo:
      Nato556: 180
    damage_multiplier: 1
    custom_flags: 
    ignore_spawn_system: false
  -
  # The maximum number of players that can have this role in this wave
    max_players: 4
    spawn_settings: 
    id: 2
    name: ''
    override_role_name: false
    nickname: ''
    custom_info: ''
    badge_name: ''
    badge_color: ''
    role: ChaosRifleman
    team: 
    role_appearance: ChaosRifleman
    is_friend_of: []
    health:
      amount: 150
      maximum: 150
      hume_shield: 0
      hume_shield_regeneration_amount: 0
      hume_shield_regeneration_delay: 0
    ahp:
      amount: 0
      limit: 0
      decay: 0
      efficacy: 0
      sustain: 0
      persistant: false
    effects: []
    stamina:
      regen_multiplier: 1
      usage_multiplier: 1
      infinite: false
    max_scp330_candies: 2
    can_escape: false
    role_after_escape:
    scale:
      x: 1
      y: 1
      z: 1
    spawn_broadcast: 
    spawn_broadcast_duration: 15
    spawn_hint: ''
    spawn_hint_duration: 0
    custom_inventory_limits:
      Medical: 2
    inventory:
    custom_items_inventory: []
    ammo:
      Nato556: 180
    damage_multiplier: 1
    custom_flags: 
    ignore_spawn_system: false
  - 
    # The maximum number of players that can have this role in this wave
    max_players: 4
    spawn_settings: 
    id: 2
    name: ''
    override_role_name: false
    nickname: ''
    custom_info: ''
    badge_name: ''
    badge_color: ''
    role: ChaosRifleman
    team: 
    role_appearance: ChaosRifleman
    is_friend_of: []
    health:
      amount: 150
      maximum: 150
      hume_shield: 0
      hume_shield_regeneration_amount: 0
      hume_shield_regeneration_delay: 0
    ahp:
      amount: 0
      limit: 0
      decay: 0
      efficacy: 0
      sustain: 0
      persistant: false
    effects: []
    stamina:
      regen_multiplier: 1
      usage_multiplier: 1
      infinite: false
    max_scp330_candies: 2
    can_escape: false
    role_after_escape:
    scale:
      x: 1
      y: 1
      z: 1
    spawn_broadcast: 
    spawn_broadcast_duration: 15
    spawn_hint: ''
    spawn_hint_duration: 0
    custom_inventory_limits:
      Medical: 2
    inventory:
    custom_items_inventory: []
    ammo:
      Nato556: 180
    damage_multiplier: 1
    custom_flags: 
    ignore_spawn_system: false
