SCP's:
Scp049
Scp939
Scp096
Scp3114
Scp0492
Scp079
Scp106

Foundation Forces: 
FacilityGuard
NtfPrivate
NtfSergeant
NtfSpecialist
NtfCaptain

Chaos Insurgency:
ClassD
ChaosRifleman
ChaosMarauder
ChaosRepressor
ChaosConscript

Flamingo: 
Flamingo
AlphaFlamingo
ZombieFlamingo

Other Roles:
Tutorial
Filmmaker
Overwatch
Spectator
